spring:
  application:
    name: hw3
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hw3}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

app:
  security:
    jwt:
      accessExpirationMs: ${JWT_ACCESS_EXPIRATION_MS:900000}  #15 min
      refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:1296000000} #15 days
      secret:
        hs_256_access: ${JWT_SECRET_ACCESS:qs5T4iesLQ9D+0VTiXrGqUDEgsVvrP3o/c1aam0vX0E=}
        hs_256_refresh: ${JWT_SECRET_REFRESH:R14CmRynq7dpgNbBJSABwFThq0Sa/SAG0BlUOdn3XKc=}