CREATE TABLE IF NOT EXISTS public.users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    varchar(250)                            NOT NULL,
    password varchar(255)                            NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT UQ_USER_USERNAME UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description TEXT,
    status      varchar(100)                            NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    CONSTRAINT PK_ORDERS_ID PRIMARY KEY (id),
    CONSTRAINT FK_ORDERS_ON_CUSTOMER_ID FOREIGN KEY (customer_id) REFERENCES public.users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id BIGINT      NOT NULL,
    role    varchar(40) NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (user_id, role),
    CONSTRAINT FK_USER_ROLES_ON_USER_ID FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);