CREATE TABLE IF NOT EXISTS public.users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email varchar(250)                            NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description TEXT,
    status      varchar(100)                            NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    CONSTRAINT PK_ORDERS_ID PRIMARY KEY (id),
    CONSTRAINT FK_ORDERS_ON_CUSTOMER_ID FOREIGN KEY (customer_id) REFERENCES public.users (id) ON DELETE CASCADE
);